import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="flex flex-row items-center justify-items-center min-h-screen font-[family-name:var(--font-geist-sans)]">
						<div className="container max-w-4xl mx-auto px-4">{children}</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
